Ported topic watcher to modular
eclipse-volttron/volttron-topic-watcher pull request #1
Opened 2023-12-01 21:31 UTC by riley206

Ported topic watcher to modular

2024-01-20 00:47 UTC, craig8 requested changes

2024-01-20 00:47 UTC, craig8 commented on src/topic_watcher/agent.py
> +from zmq import ZMQError
This can't rely on zmq at all

2024-02-23 19:22 UTC, craig8 commented
@riley206 did you remove the zmq references...

2024-02-23 19:54 UTC, riley206 commented
> @riley206 did you remove the zmq references...

Sorry, I totally missed that.

2024-02-28 20:01 UTC, schandrika commented
@riley206 Please update tests to install agent from local dir not from pip.  Currently I cannot run the tests at all as there is no topic watcher in pypi. But even after we push the agent to pypi, test should install and test local copy.
Instead of pip install volttron-topic-watcher, do pip install <relative-path>/volttron-topic-watcher. Get path using current file location, for example - agent_path = Path(__file__).parents[1]

2024-02-28 20:02 UTC, schandrika commented
@riley206  Also please look at pep8 warnings. At least some of the them can be easily fixed - unused import, wrong indent, unreachable code etc

2024-02-28 20:45 UTC, schandrika commented
instead of using non existent " utils.is_secure_mode()"  use ClientContext.is_secure_mode() 
this way you can also get rid of the "if False" and hence the unreachable code

2024-02-29 00:43 UTC, schandrika commented
missing docs - please add docs

2024-03-11 15:46 UTC, riley206 commented
> @riley206 Also please look at pep8 warnings. At least some of the them can be easily fixed - unused import, wrong indent, unreachable code etc

I ran it through the pep8 linter black.

2024-03-11 15:47 UTC, riley206-pnnl commented
> instead of using non existent " utils.is_secure_mode()" use ClientContext.is_secure_mode() this way you can also get rid of the "if False" and hence the unreachable code

do I need to import something for this?

Edit - I found the correct import.

2024-05-03 21:38 UTC, schandrika requested changes
1. agent.py hardcodes vip id to platform.topic_watcher. This will make code fail on start if the default vip id is used
2. Missing config.py in docs/source. without this you can't run make html locally. See postgresql historian. you can copy paste code from there
3. Update to newer version of sphinx - again refer to postgresql historian

2024-05-07 19:29 UTC, schandrika commented
@riley206 Could you test the scenario where you install the agent without config and add config through config store. The config updates doesn't seem to have any effect.  Could you please test this use case

2024-07-30 23:42 UTC, merged